title: Warsztat Samochodowy Perfect Car
description: "Kompleksowa obsługa samochodów. Mechanika samochodowa, diagnostyka i serwis. Myjnia ręczna, kosmetyka samochodowa. Tczew, ul. Rokicka 17,  tel. 731 548 948."
baseurl: "" 
url: "https://perfectcar.tczew.pl" 

facebook_url: https://pl-pl.facebook.com/Perfect-Car-165492297470892/
phone_url: +48731548948
google_url: https://g.page/perfectcar-tczew?share
e-mail_url: biuro@perfectcar-tczew.pl

logo: perfect-car-logo-web-360.png
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
highlighter: rouge
excerpt_separator: |2+

sass:
  sass_dir: _sass/
  style: compressed
  
exclude:
- Gruntfile.js
- Gemfile
- Gemfile.lock
- package.json
- package-lock.json
- README*
- node_modules
- ".gitignore"
